### PR TITLE
ENH: Switch build system to CMake

### PR DESCRIPTION
**Pull request by hhslepicka**
Experiment with cmake as the build system.
So far it builds the main library (libsrw.a) and the python client (srwlpy.so).
The python client fails at import with a segfault... I am trying to investigate why that is happening.
Focus so far is to get the most simple SRW to work with this setup before going into OpenMP build as well but the whole mechanism is in place already.

The idea is to follow https://www.benjack.io/2017/06/12/python-cpp-tests.html on how to use cmake inside of setup.py to have a consistent build process if users decide to go with the python package or just regular C code.

Opening this PR as Draft so work is transparent.

Build Instructions:
```
mkdir build
cd build
cmake .. -DBUILD_CLIENTS=ON -DBUILD_CLIENT_PYTHON=ON -DBUILD_CLIENT_C=ON
make
```

If one is interested only on the Python client, the build instructions are:
```
cd python
python setup.py install
# or for OpenMP version:
MODE=omp python setup.py install
```

TODO
------
- [x] Test on Windows for regular build
- [x] Test on Windows for OpenMP (not sure if possible)
- [x] Documentation on how to install
- [x] Documentation for CMake options
- [x] Cleanup client build. Remove -DBUILD_CLIENTS=ON and rely on explicit client build instructions.

### CODE REVIEW

**Comment by hhslepicka** [comment]
The issue with the python client build was addressed. Now I am working on making the setup.py issue a cmake command to build the extension. This will allow us to have a single source of truth for all things build.

**Comment by hhslepicka** [comment]
First successful example with srwpy using cmake and setup.py with CMakeExtension:
image

The package was installed with: `python setup.py install`... Now to investigate why `pip install .` is failing....

**Comment by hhslepicka** [comment]
Current version with cmake working properly for Linux and Mac building both regular and OpenMP versions.

**Comment by hhslepicka** [comment]
Success running cmake on Windows for regular version of the code so far.
Still missing OpenMP version. To be done soon...

**Comment by hhslepicka** [comment]
Success with Windows build via using FFTW library available online on Oleg's repo. I can't find a non-hacky way to build FFTW 2.x in Windows without much workarounds.

**Comment by hhslepicka** [comment]
@mrakitin and @christophermayes I think this branch is ready for some tests.

Please keep in mind that you will need cmake >= 3.12.
For that you can install it with:
```
conda install -c conda-forge cmake
```

To install the Python client please just do:
```
cd python
python setup.py install
```

After that you can run the examples inside of SRW:

```
cd examples/python
python SRWLIB_Example01.py
```

**Comment by hhslepicka** [comment]
@mrakitin do you know if SRW makes any distinction of version number? Other than hardcoded into setup.py I don't see anything else.

**Comment by mrakitin** [comment]
https://github.com/ochubar/SRW/search?q=version&type=code uncovered a few versions, mostly for IgorPro - 3.96(5). What I did for srwpy was to create a version in the YYYY.MM.DD format corresponding to the date a commit was pushed.

**Comment by hhslepicka** [comment]
@mrakitin got it... we can decide on that once we have a meeting with Oleg and maybe propose a new version scheme with numbers and leverage of GitHub releases.
Do you mind taking it for a spin and some tests?

**Comment by mrakitin** [comment]
Thanks @hhslepicka, it will happen sometime next week.

**Comment by hhslepicka** [comment]
@mrakitin sounds good! 
Do you happen to have access to a Igor Pro with XOP license?

**Comment by mrakitin** [comment]
@hhslepicka, no, unfortunately, no. I remember a few licenses were purchased by Oleg, and I used to use one in 2015-2017, but don't have it now. Maybe @ochubar can recommend?

**Comment by hhslepicka** [comment]
@mrakitin any updates on tests? do you think you will have the bandwidth to do it? 
If not, i will merge this PR into the reorg branch and move ahead with the remaining work.

**Comment by mrakitin** [comment]
Sorry, got distracted on Tuesday, and did not have a chance to get back to that. I'll run the tests anyway.

**Comment by hhslepicka** [comment]
no problem... if you find anything feel free to open an issue or put up a PR.

**Pull request merged**
